### ISSUE TITLE
CI: conda envs sporadically fail to install

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#12]
e.g. https://github.com/bioimage-io/collection-bioimage-io/actions/runs/1412847836/attempts/1
```
Run conda-incubator/setup-miniconda@v2
Gathering Inputs...
Creating bootstrap condarc file in /home/runner/.condarc...
Ensuring installer...
Setup environment variables...
Parsing environment...
Configuring conda package cache...
Applying initial configuration...
Initializing conda shell integration...
Adding tools to 'base' env...
Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```

It may be related to the (for the CI experimental) mamba solver.
@constantinpape  any idea?

**Comment by constantinpape** [comment]
No idea; might be related to mamba ...
To debug, you could check if there's a verbose option in setup-miniconda.

**Comment by FynnBe** [comment]
that's a great idea. looking at it again I now noticed what I think is the source error in the error log:
```CondaHTTPError: HTTP 503 SERVICE TEMPORARILY UNAVAILABLE for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>```
 
 It seems to be a known issue for which the solution is to wait: https://github.com/conda/conda/issues/7800
 
It'd be great if we could just retry in the CI and not run all jobs again...

**Comment by FynnBe** [comment]
Let's see how often this really happens. Currently the CI runs twice a day, so if it occasionally fails it's not too bad.
