### ISSUE TITLE
Inconsistent generated rdf.yaml vs collection spec

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#211]
the generade rdf.yaml collection lists resources under the `attachment` key, while the collection spec defines the resource fields `application`, `model`, `dataset`, `notebook` under root. Adding anything under `attachment` is not invalidating the collection rdf, but if validating it (which we don't directly do) would ignore anything under `attachment`, while it would validate content under the resource fields. 

generated collection rdf:
https://github.com/bioimage-io/collection-bioimage-io/blob/a19daf9c456072c57474dd2d04a033be9d6675b2/rdf.yaml#L1-L2

**Comment by oeway** [comment]
Letting the type keys spread under the root won't allow the website implement a type-agnostic collection display, so I would rather change the collection spec. And absorb the collection spec as part of the general RDF to enable recursion of RDFs.

**Comment by FynnBe** [comment]
we solved this with the collection RDF 0.2.2
