### ISSUE TITLE
Skip creating PR for items from community partners

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#213]
I am now thinking that maybe we don't really need to create any PR for items coming from the partners / GitHub. If we consider these are trusted partners, we can basically  pull them directly and render directly to the website.

This will be appropriate if we assume the partners will do their job in validating the items that goes to their repo. The approval process of the collection repo will be done by community partners anyway, we won't need to approve it twice.

This can greatly simplify implementation and maintenance if we only do approval for untrusted items from zenodo.

Comments? Thoughts?

**Comment by FynnBe** [comment]
This might lead to a lot of "failing" resources on the website. If we filter these out by default as discussed in previous meetings I don't see a problem if we keep running the validation here for consistency

**Comment by oeway** [comment]
To clarify, we still do validation here for all the resources displayed on the site but we don't do approval and PRs for items from partners and we don't save them in the collection folder in the main branch. The approval process is done by the partners, and there we also have CI running even with more consumer specific validation and tests.
