### ISSUE TITLE
validation summaries are not yet included in final collection RDF

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#220]
the summaries are already deployed to gh-pages and the validation is also taking place in the PRs. Only including it in the final collection to render on the website is not working yet.

cc @oeway @constantinpape

**Comment by FynnBe** [comment]
fixed

**Comment by oeway** [comment]
@FynnBe Let me know when you fixed the CIs, I might need to make some changes in the website.

**Comment by FynnBe** [comment]
> @FynnBe Let me know when you fixed the CIs, I might need to make some changes in the website.

@oeway yeah... fixed 🎉
