### ISSUE TITLE
PR for new model is not submitted

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#221]
I uploaded a new model yesterday: https://zenodo.org/record/5847356#.YeE4c_so8UE
But it seems like the PR for it is not appearing here.

**Comment by FynnBe** [comment]
Cron schedule was deactivated... Should be fixed now

**Comment by FynnBe** [comment]
I suppose you were expecting #222

**Comment by constantinpape** [comment]
> I suppose you were expecting #222

Yes, exactly.
