### ISSUE TITLE
Wrong model name

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#241]
The model name for https://github.com/bioimage-io/collection-bioimage-io/blob/main/collection/10.5281/zenodo.5817052/resource.yaml is wrong: this is not a mitochondria segmentation model, but a neuron segmentation model.
See
![image](https://user-images.githubusercontent.com/4263537/149623091-9f93aa0b-cb74-4afa-a332-ac4a4ff0d772.png)

This looks pretty bad because it is the first model on the website and clearly wrong....
We could try fixing this on the fly by changing the name in the yaml in this repo or we need to update the version via the website / zenodo.

cc @esgomezm

**Comment by esgomezm** [comment]
Ups! I was confused with the data for the 3D UNet. I should be able to update it by clicking on the edit button, but I don't see the model on the webpage

**Comment by constantinpape** [comment]
> Ups! I was confused with the data for the 3D UNet. I should be able to update it by clicking on the edit button, but I don't see the model on the webpage

Yes, @oeway is aware of that issue and currently fixing it.

**Comment by esgomezm** [comment]
So, the page works and I can click on edit, but then, i cannot update the model card, at the end of the process. It just allows me to upload a new deposit

**Comment by oeway** [comment]
> So, the page works and I can click on edit, but then, i cannot update the model card, at the end of the process. It just allows me to upload a new deposit

OK, I will check that.

**Comment by oeway** [comment]
@esgomezm @constantinpape I just did a preliminary fix for the edit button, but I cannot test it since it requires existing items. could you try with 0.4.5 (refresh here: https://bioimage.io/#/about until you see 0.4.5)?

**Comment by constantinpape** [comment]
Yes, it's working now :).

**Comment by oeway** [comment]
@esgomezm and @constantinpape Do we have a plan on updating this model, I still see "mitochondria" in the model description.

**Comment by constantinpape** [comment]
As we discussed during the meeting @esgomezm wanted to check if update via the upload still works.

**Comment by esgomezm** [comment]
Hey! I'm trying model edition and it goes well until the update button but then it complains about a field called `rdf_source`.
![Screenshot 2022-01-26 at 14 43 41](https://user-images.githubusercontent.com/43643518/151184249-5e998ebd-3ef5-4baf-be1d-e8d43509ff28.png)

![Screenshot 2022-01-26 at 14 43 24](https://user-images.githubusercontent.com/43643518/151184201-733457f8-4724-4150-acaa-27f8d61fffcd.png)

**Comment by oeway** [comment]
@esgomezm Thanks for the report, it should been fixed now in 0.4.7 (https://bioimage.io/#/about), please refresh the page and try it again.

**Comment by esgomezm** [comment]
Done! now should I see any PR?

**Comment by constantinpape** [comment]
> Done! now should I see any PR?

Yes, I think it's this one: https://github.com/bioimage-io/collection-bioimage-io/pull/265

**Comment by constantinpape** [comment]
I have merged #265 and this is fixed now.
