### ISSUE TITLE
Test summary for the website

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#257]
The CI generates validation summary in gh-pages, however, I am a bit confused now because I can only find summaries labeled as `static` or `latest_static`. @FynnBe Where are the dynamic ones?

Since we have 1 subfolder per version and the summaries are contained in the subfolder, shouldn't it only contain a single static summary?

And for the dynamic summaries, can we have 1 file per environment combination?

For rendering on the website, I would like to have something like this compiled into the rdf.yaml:
```yaml
config:
    bioimageio:
    test_summary:
        status: passed # or failed/skipped, but I would like to have something explicit rather than "no error means passed"
        tests:
            - name: Static RDF validation
               description: Static RDF validation with bioimageio.spec validate command
               status: passed
            - name: Dynamic Test (TorchScript/Python 3.8)
               status: failed
               error: ...
               traceback: ...
```

Besides, I think it's better to call the ultimate summary field `test_summary` so it can contain validations and other tests.

Edit: changed `steps` to `tests` as suggested by @FynnBe

**Comment by FynnBe** [comment]
on the name: 
the dynamic test is also validation: we validate that the test output can be reproduced... but if you'd prefer test_summary we can totally change it!

This change means that we always have to resave the rdf.yaml to insert the summary there. If we do that we don't have to save any of the individual validation summary files at all... 

I see a remaining issue that is related to this with the saving of the rdf.yaml as the saved rdf.yaml is not a valid rdf. We should fix that either by accepting any URI for fields that currently expect local relative paths or in a different manner that I just haven't thought of yet.

**Comment by FynnBe** [comment]
> Where are the dynamic ones?

There are not generated if the latest static one has an error....

**Comment by FynnBe** [comment]
about the `steps`:
some tests may depend on other tests (like dynamic ones on latest static), but they are not necessarily ordered. Should we use the name as a dict key instead similar to what we have now? and maybe call it `tests` instead of `steps`?

**Comment by oeway** [comment]
hi, for the name test summary, I think it will be more general for cases when a consumer add custom tests that are not necessary validations.

> This change means that we always have to resave the rdf.yaml to insert the summary there. If we do that we don't have to save any of the individual validation summary files at all...

Sounds good!

> I see a remaining issue that is related to this with the saving of the rdf.yaml as the saved rdf.yaml is not a valid rdf. We should fix that either by accepting any URI for fields that currently expect local relative paths or in a different manner that I just haven't thought of yet.

Why not valid? Could you elaborate ? I tried one before and it was valid. 

> some tests may depend on other tests (like dynamic ones on latest static), but they are not necessarily ordered. Should we use the name as a dict key instead similar to what we have now? and maybe call it tests instead of steps?

I'd prefer a list since on the website we want a ordered list display since we don't want to see dynamic tests showing before static tests. Ideally, the CI should figure out the order of the list, the website should stay agnostic to the actual tests. Plus, have a unique key for each tests seems unnecessary. Even if the order doesn't matter for some tests, we can always save by the order of completion the test. 

However, change steps to tests sounds good.

**Comment by FynnBe** [comment]
> Why not valid? Could you elaborate ? I tried one before and it was valid.

relative local paths either are converted to urls or kept and thus point to files that don't exist.

> I'd prefer a list since on the website we want a ordered list display, for example we don't want to see dynamic tests showing before static tests. Ideally, the CI should figure out the order of the list, the website should stay agnostic to the actual tests. Plus, have a unique key for each tests seems unnecessary. Even if the order doesn't matter for some tests, we can always save by the order of completion the test.

sounds good 👍

**Comment by FynnBe** [comment]
https://github.com/bioimage-io/collection-bioimage-io/pull/262 should implement all changes discussed here...
