### ISSUE TITLE
Validation broken due to invalid generated rdf.yaml 

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#258]
For each resource we generated an rdf.yaml file in gh-pages/resources/... 
But these rdf.yaml files are not valid RDFs due to resolved paths where we expect local relative paths. We either have to 
 - change the spec to make them valid 
 - or stop treating them as real RDFs (which at this point would be very confusing) and validate the original source (with updates from the collection entry (which we were doing a week or so ago...? ;-) )

**Comment by oeway** [comment]
I think change the spec would make sense here. It's a non-breaking change, right? Could you give some examples on which fields only accepts relative path? Have a unified way of handling URI/path would be good in general. We just need to make sure the bioimageio.core also resolve absolute path.

**Comment by constantinpape** [comment]
I don't fully understand this issue yet.
@FynnBe can you please point to what exactly is the issue with the generated rdf, i.e. point to a line in one of the files?
Otherwise I agree with Wei, it sounds like we should fix this on the spec level somehow.

**Comment by FynnBe** [comment]
my bad, we changed that already... Maybe I was mistaken that this is the problem...
