### ISSUE TITLE
Design ideas for improving the pull request process

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#26]
We eventually want a single PR per model that is added to the model-zoo. I think to implement this model, we should change the system s.t. the PR creates a single file. This would avoid merge conflicts.

We could still consolidate it into a single file later (e.g. another CI puts the merged models into the main yaml file periodically.)

**Comment by FynnBe** [comment]
👍 Thus actually mirrors what we do for the test summaries already

**Comment by oeway** [comment]
I think it's a good idea, caching this file will also allow us to, remember the current zenodo version and add additional tags etc.

**Comment by FynnBe** [comment]
#29 implements this
