### ISSUE TITLE
Enable a "beta" setup to run in development without breaking the website or the model PRs

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#269]
Probably the easiest is to create a personal fork and set up the correct CI tokens.
cc @FynnBe @oeway

**Comment by FynnBe** [comment]
I have set up a fork (not fully working yet, I went straight away to develop on its main...)
It will be up and running soon. Feel free to make PRs there if you don't want to set up your own fork. Especially right now as I am developing there and touching a lot of the code this might also avoid merge conflicts...
