### ISSUE TITLE
Invalid deps for accepted resource

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#280]
https://github.com/bioimage-io/collection-bioimage-io/blob/3caf9e0bee8b6616ae01739c22bdddd831938052/resources/10.5281/zenodo.5764892/10.5281/zenodo.5764893/rdf.yaml#L82

points to an invalid [environment.yaml](https://zenodo.org/api/files/8137780b-871f-4d7e-b130-a63847ece4d8/environment.yaml)

Not sure how we didn't catch this earlier, but I encountered it on my fork...

**Comment by FynnBe** [comment]
the problem with the env file is that dependencies is not a list

**Comment by constantinpape** [comment]
Yes, this was an issue in all my models. Indeed it's weird that the CI hasn't caught it before.
Should be fixed by #281. I will update the other models once we are sure that this one works.
