### ISSUE TITLE
Nucleus model not available on the website

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#294]
The nucleus segmentation model (https://zenodo.org/record/6028056#.YheQ5hso8UE) is currently not available on the website, although it is accepted (and it has been listed before):
https://github.com/bioimage-io/collection-bioimage-io/blob/main/collection/10.5281/zenodo.5764892/resource.yaml

It should e.g. show up when looking for the "nuclei" tag:
![image](https://user-images.githubusercontent.com/4263537/155540391-750fb059-9744-494b-82fe-39b3cb57c37e.png)

**Comment by oeway** [comment]
For some reason this item (10.5281/zenodo.5764892) is not in the generated summary on gh-pages so that explains why the website did not show it. @FynnBe

**Comment by FynnBe** [comment]
I'm on it...

**Comment by constantinpape** [comment]
Something that might be relevant here: the model currently fails static validation (this is due to the new check for min shape and halo that we have introduced; in hindsight it was not a good idea to do this independent of model versioning....)
I wanted to update it via the website to fix this, but maybe it's not shown due to this issue?

**Comment by constantinpape** [comment]
This is fixed now.
