### ISSUE TITLE
Set the `source` URL in the generated RDF

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#310]
The downloader failed to work due to missing source field in the updated rdf.yaml. 

In the updated rdf.yaml file, for example: https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.5847355/5874728/rdf.yaml  we need to set the `source` field or the `rdf_source` field to the original zenodo rdf url, without that, there is no way to infer the base URL for downloading the weights files etc.

@FynnBe Please look into this, and this is urgent since it's prevent any model downloads from the website.

**Comment by FynnBe** [comment]
@oeway should we instead populate the updated rdf with urls only to nothing else needs to be resolved? (I intended that that was already happening...)

**Comment by oeway** [comment]
I would suggest we take it easy change one thing at a time, I don't know whether it will cause further issue. It might break stuff since when since after downloading the file we need to change it back to relative path. Again the top priority is to restore the website.

**Comment by FynnBe** [comment]
for the weights source we even state "Preferably a url." https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/weight_formats_spec_0_4.md

**Comment by FynnBe** [comment]
Are you sure URLs wouldn't already work? some fields have always allowed path or URL, so the downloader should be able to deal with it. The downloader itself is also easy to update, is it not? No netlify deployment, etc..

I'd rather put in the URLs right away, as this is just the most straight forward solution. The updated RDFs in gh-pages should be valid and with relative paths they are missing files and thus are invalid...
Additionally this is very different for zenodo and partner resources, which makes these changes unnecessarily complicated. Right now all resources no matter where they're from have their updated rdf source on gh-pages. Single source of truth! :-)

I do grab that coffee though. At the end of one cup we will have fixed all this ;-)

**Comment by oeway** [comment]
> Are you sure URLs wouldn't already work? some fields have always allowed path or URL, so the downloader should be able to deal with it. The downloader itself is also easy to update, is it not? No netlify deployment, etc..

As I said, I don't know it will not break other stuff. 

I don't really care how we fix it, I just want to fix the website as soon as possible. The calculation for me is simple, it takes a minutes to add a source field and the downloader will work as before. And my suggestion is to restore first, then optimize. I have limited time on this today. But if you want to go for the harder way, I have no objection, please make sure you do the following:
 * Update and test the downloaders, make sure you clear the browser cache when you test them
 * Sending PRs to update the downloader in the imjoy repo, ilastik repo and deepImagej repo
 * Make sure you tested all the downloaders with several models and ideally test whether the downloaded packages works in the corresponding software
 * Make sure you test other website features like links, apps etc.

**Comment by FynnBe** [comment]
(works as is with urls in the updated rdf and rdf_source pointing to the updated rdf on colleciton's gh-pages)

**Comment by FynnBe** [comment]
pushed the partial reset also here https://github.com/bioimage-io/collection-bioimage-io/commit/f9918f68ae69f32ecfaf1c041ab1ab3b950a3dce
