### ISSUE TITLE
Cover image URL not resolved

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#319]
Some cover images are broken because the URL to zenodo are not resolved in the generated summary: https://bioimage.io/#/?id=10.5281%2Fzenodo.5914248

@FynnBe Could you please look into this?

**Comment by FynnBe** [comment]
reset: https://github.com/bioimage-io/collection-bioimage-io/commit/45031581b4f7ca96d18d7ef3cf84c4c5f5607622

**Comment by FynnBe** [comment]
ah, the issue is that it does not pass static validation and therefore does not resolve the original relative file paths to urls:
https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/rdfs/10.5281/zenodo.5914248/5914249/test_summary.yaml

**Comment by oeway** [comment]
> ah, the issue is that it does not pass static validation and therefore does not resolve the original relative file paths to urls: https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/rdfs/10.5281/zenodo.5914248/5914249/test_summary.yaml

Can we make the generation of URLs independent from the validation?

**Comment by FynnBe** [comment]
> Can we make the generation of URLs independent from the validation?

With invalid data it is difficult to know which field to turn into a URL and which not. It surely is possible, but I am not sure this is worth our time right now, while we should just fix the static validation errors anyway...

**Comment by oeway** [comment]
> With invalid data it is difficult to know which field to turn into a URL and which not. It surely is possible, but I am not sure this is worth our time right now, while we should just fix the static validation errors anyway...

Well, this is rather important for us, it makes the website looks broken for the moment. And we know exactly which fields are needed for the website to display correctly. Basically two fields: `rdf_source` and `covers` are always needed to be rendered as card.

And I am not sure if it's only about fixing the static validation error. In an ideal world yes, but in reality, we are changing the validator all the time, it can also because some issue with the validator itself.

So for me, we should always try to resolve the RDF, even if the validator fails to validate the item. If we cannot resolve the RDF item, we should remove the item from the website so we don't end up with a broken resource card.

**Comment by FynnBe** [comment]
we should
- [ ] fix partner collections (also see https://github.com/bioimage-io/spec-bioimage-io/issues/413)
- [ ] fix static validation for currently accepted resources
- [ ] attempt to resolve essential fields even if validation fails (`rdf_source`, `covers`, `name`, ...?)
- [ ] hide resources from bioimage.io that don't have valid essential fields
- [ ] hide (or mark) resources from bioimage.io that do not pass static validation

**Comment by FynnBe** [comment]
https://github.com/bioimage-io/collection-bioimage-io/pull/377 ensures that the PR CI run fully incorporates the update from the resource.yaml in the collection folder. This ensures that we can fix failing static validation in a PR. With static validation passed all remote resources are resolved correctly. The updated RDF with the resolved URLs is deployed to gh-pages. This should ensure that fields like `covers` hold appropraite URLs and not invalid local paths.
Please reopen if this is not sufficient
