### ISSUE TITLE
The website is entirely down

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#412]
@FynnBe It looks like the recent changes breaks the entire thing:
<img width="1532" alt="Screen Shot 2022-05-04 at 8 05 27 PM" src="https://user-images.githubusercontent.com/478667/166774603-1bd2d2af-e93d-476a-bdde-357f7f7f7f2b.png">

Would be nice if we can fix this ASAP.

**Comment by FynnBe** [comment]
yes, I am on it. sorry

**Comment by FynnBe** [comment]
I tried the fast hacky fix -- it didn't work.. If I don't have things back to normal very soon I'll reset it to the state before...

**Comment by FynnBe** [comment]
> it's not yet back 100%, but it is very close.. working on the remaining issues still

actually only CI had to finish running. it's all back now

**Comment by oeway** [comment]
Hey, good that it's back! Thanks!

We need to get the deepimagej models back too.

**Comment by FynnBe** [comment]
I think they are all back now, e.g. https://bioimage.io/#/?type=all&partner=deepimagej&id=deepimagej%2Fsmlm-deepimagej
Feel free to re-open if I am missing something

**Comment by oeway** [comment]
Oh, sorry, wrong link, ignore that URL,

For example this one: https://github.com/deepimagej/models/blob/cdbf04f54784b645448b1b24d2b5a7a2e10fb4db/manifest.bioimage.io.yaml#L184-L191

**Comment by FynnBe** [comment]
ok, I'm working on fixing it. I found the issue already. It needs some general imrovements...
