### ISSUE TITLE
Create "generic" partner collection

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#421]
to host applications or other resources for partners that don't have a dedicated repo yet.
The first two things we want:
- application for stardist
- application for qupath

**Comment by oeway** [comment]
Let's use the previous repo for this: https://github.com/bioimage-io/bioimage-io-models

We can just modify the yaml file there.

**Comment by oeway** [comment]
Done! Feel free to add the items there: https://github.com/bioimage-io/bioimage-io-models

**Comment by oeway** [comment]
> jtlyk: I renamed it to https://github.com/bioimage-io/bioimage-io-resources, however the link https://github.com/bioimage-io/bioimage-io-models is still valid as we plan to predominantly add any non-model resources there...

Saw that, looks good to me! 

However, for the yaml file name, I think it would nice to still keep `bioimage.io` in they yaml name to have better identification of the file. I would rename the yaml file to something like `collection.bioimage.io.yaml` instead of `colleciton.yaml`.

**Comment by oeway** [comment]
This has been fixed.
