### ISSUE TITLE
deletion of partner resources

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/collection-bioimage-io#482]
as encountered in https://github.com/bioimage-io/collection-bioimage-io/issues/481 we may delete resources that were linked in partner collections.

In this case, should they just disappear (resulting in invalid old links) or should we add a placeholder?
In this particular case (model on zenodo and in partner collection) it would make sense to refer to the remaining (zenodo) model card... 
     
I think the simplest is to just remove the item and accept broken links. If one wants to refer to another resource and avoid broken links, then resource should simply not be deleted, but instead its description adapted accordingly (referring to another resource, etc..).

We only talk about partner resources from the partner collection here.
Any (strong) opinions out there @oeway @constantinpape ?

**Comment by esgomezm** [comment]
Hey there, 

Not sure technically what's the best way to go, but I thought that the collection workflow processed the yaml file completely each time it's compiled. So if a model "suddenly disappears" from the yaml, it will not be displayed in the next round.

**Comment by FynnBe** [comment]
> ...but I thought that the collection workflow processed the yaml file completely each time it's compiled. So if a model "suddenly disappears" from the yaml, it will not be displayed in the next round.

almost. we do keep state. however, how we solve this technically does not imply what we want. 
but yes, we can simply drop removed resources. I think this would be best. Maybe everyone was expecting this anyway I suppose.. 
I'll implement it like that. As an example, this will break this link: https://bioimage.io/#/?type=all&utterances=1a2565da59cc97568a382308zgepWORi306OLMNNaA6XhejLxk9hOXnATEr2YHP%2FfmuAapxw145ruzq9bjd%2BCxfKn1snBkZWdppRqFOpZ0hKYjQpchN1RjUXqZnwE6sI3YEvDN7gcRcz7ElKRlw%3D&tags=usii&id=deepimagej%2Fusiigaci

**Comment by FynnBe** [comment]
#483 now marks partner resources as deleted, they will not show up in the rdf.json anymore and thus not render on the website, but on the gh-pages there will still be a `resource.yaml` under `partner_collection` with `status=deleted`. Once in a while we might reset gh-pages; then these would dissappear completely. similarly the version specific rdf.yaml files will stay on gh-pages until a reset.
