### ISSUE TITLE
URGENT: Partner logos disappeared

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#491]
@FynnBe Your recent changes to the collection repo removed the partner config (logo, background etc.) this cause issues on the website, all the partners loges are gone etc.

For reference, this is how the partner field should look like: https://github.com/bioimage-io/collection-bioimage-io/blob/20189e7d3e5ce5164fd1f87a38dc3036fc0700b6/rdf.yaml#L2459-L2477

And this how it looks right now: https://github.com/bioimage-io/collection-bioimage-io/blob/604c7720889fad957fd684ab16c2c81b2056169b/rdf.yaml#L2302-L2320

This is high priority, we should not let the website broken for too long. 

Thank you!

**Comment by FynnBe** [comment]
hi @oeway , good that you noticed so quickly! it's fixed now:
https://github.com/bioimage-io/collection-bioimage-io/commit/6611b56aaea622565213aed5cb3bc6b15a059480
