### ISSUE TITLE
N2V2 submission

### ISSUE THREAD

**Issue by jdeschamps** [bioimage-io/collection-bioimage-io#517]
Hey! 

I tried uploading a model few weeks ago and made a mistake during the Zenodo upload: https://github.com/bioimage-io/collection-bioimage-io/pull/513

Since then I updated the model on Zenodo: https://zenodo.org/record/7386107

I don't have a clear view of the process yet, but I was expecting a new pull request (which is not what is happening). What can I do next? :)

**Comment by FynnBe** [comment]
@esgomezm accidentally blocked the whole resource, not just the version:
https://github.com/bioimage-io/collection-bioimage-io/pull/513/commits/a5ac2d1d671855987fdf14160cd5cc7924aeaad5
