### ISSUE TITLE
Updating a model retains previous rdf.yaml

### ISSUE THREAD

**Issue by ivan-ea** [bioimage-io/collection-bioimage-io#549]
A new version of the `wild-whale` model was uploaded by its maintainer @constantinpape. 
It appers [in the collection](https://github.com/bioimage-io/collection-bioimage-io/tree/gh-pages/rdfs/10.5281/zenodo.6079314/7688686) and in the [web page](https://bioimage.io/#/?tags=epithelia&id=10.5281%2Fzenodo.6079314).

The problem is that the rdf was not updated (seems like the old one, with the bioimageio version bumped), the new weights, deepimagej config, and sample tiffs are missing. Do you know why this could be happening @FynnBe  @oeway?

**Comment by FynnBe** [comment]
the latest version only has pytorch weights.. I assume this was done on purpose by @constantinpape

**Comment by constantinpape** [comment]
No, this is not on purpose; I have updated it with a version provided by @ivan-ea that should provide both pytorch and torchscript weights. I will double check this later and then follow up here.

**Comment by constantinpape** [comment]
Ok,I understand why this happened, but I think there is something wrong in the uploader ...
I have a work-around for now, and will open a separate issue on the suspected bug.
