### ISSUE TITLE
PR is not opened

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#550]
I updated a model: https://zenodo.org/record/7689587#.ZADyJ4DMKEA
But the PR for the newest version (v4) is not being opened.

Any ideas why @FynnBe @oeway?

(This is one of the models we want to update for the rebuttal, would be good to fix this soon.)

**Comment by FynnBe** [comment]
oh, I see @oeway already triggered it manually, but it failed due to:
```
403 Client Error: rate limit exceeded for url: https://api.github.com/repos/bioimage-io/icy-bioimage-io/commits/main
```

**Comment by FynnBe** [comment]
We've been using CI a bunch these days I suppose... Let's see if the 3am scheduled run works...

**Comment by FynnBe** [comment]
> 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/bioimage-io/icy-bioimage-io/commits/main

btw, in the past this error didn't abort the process, but lead to the partner logos to disappear...

**Comment by constantinpape** [comment]
> If you updated directly on Zenodo the collection CI is not triggered automatically (only runs once every 24h, if there are no additional triggers from the bioimage.io uploader)

I uploaded via bioimage.io, and not via zenodo.

**Comment by FynnBe** [comment]
ah, probably around 17:00 CET? Looks like @oeway didn't trigger manually at that time, but it was the bioimage.io uploader. 
We ought to change it such that @bioimageiobot 'manually' triggers the CI in these cases... 
Result is the same, we ran into the 403

**Comment by constantinpape** [comment]
> ah, probably around 17:00 CET?

Yep.
