### ISSUE TITLE
QuPath would like to join as a community partner

### ISSUE THREAD

**Issue by petebankhead** [bioimage-io/collection-bioimage-io#564]
### Description of your software, organization, company or team

QuPath is open-source software for bioimage analysis and digital pathology.

* **Website:** https://qupath.github.io
* **GitHub:** https://github.com/qupath/qupath
* **Docs:** https://qupath.readthedocs.io/en/0.4/
* **Forum (image.sc):** https://forum.image.sc/tag/qupath

### Description of the resources that you plan to contribute. Please also include the url to your project repo

We don't currently have 'resources' to contribute, but we aim to enable QuPath to support Bioimage.IO models, and both create (and encourage users to create) models following the Bioimage.IO spec in the future.

Work so far includes:
* [QuPath Bioimage Model Zoo extension](https://github.com/qupath/qupath-extension-bioimageio)
  * Documentation [here](https://qupath.readthedocs.io/en/0.4/docs/deep/bioimage.html)
* [QuPath BioImage Model Zoo Spec](https://github.com/qupath/qupath-bioimageio-spec)
  * Model spec parsing with minimal dependencies (well, snakeyaml, slf4j-api and, less minimally, Gson).
  * We'd be happy to transfer & rename the repo, and/or work with others to make it as generally useful as possible.

QuPath logos of different sizes are [here](https://github.com/qupath/qupath/tree/v0.4.3/qupath-gui-fx/src/main/resources/icons).

### Description of future plans on how your project will be maintained

QuPath is developed and maintained by my group at the University of Edinburgh. We have existed for more than 6 years, and are grateful to CZI and the Wellcome Trust for funding to help us continue to exist for some more :)

Currently, I am working on QuPath with @finglis (with some more people to join us soon).

### Caveat

I see the [Responsibilities](https://bioimage.io/docs/#/community_partners/README?id=responsibilities) of a community partner include:
> Use BioImage.IO as their only primary trained model repository

Currently, we host some models [here](https://github.com/qupath/models/tree/main/stardist) (actually, just two StarDist models that have been converted to frozen TensorFlow models using `tf2onnx`... but not to `onnx`, because that somehow didn't work).

The reason is that QuPath includes OpenCV by default - and this supports using some models in a very straightforward way with no additional dependencies (via the [OpenCV DNN module](https://docs.opencv.org/4.x/d2/d58/tutorial_table_of_content_dnn.html)). Previously, it has proven to be much easier to use OpenCV for inference compared to TensorFlow, PyTorch etc, since nothing extra needs to be downloaded or installed. This might change in the future, but for now we'd like to continue to support sharing models that are OpenCV-friendly.

(Of course, if we can do that by making OpenCV-compatible weights available through Bioimage.IO that would be even better :) )

**Comment by oeway** [comment]
Hi @petebankhead Thanks for the request! On behalf of the BioImage.IO admin team, we welcome you as a community partner.

For the next steps, could you please create a repository under QuPath org to host the collection yaml file? Here you can find more detailed steps: https://bioimage.io/docs/#/community_partners/how_to_join

You can skip the imjoy plugin file for now, I will help you with that.

cc @esgomezm

**Comment by esgomezm** [comment]
Hi @petebankhead 

Thank you! This is super cool 🤩!

To make it easy, you need to create a `collection.yaml` similar to the [one Icy just created ](https://github.com/bioimage-io/icy-bioimage-io/blob/main/collection.yaml) (this is the simplest one at the moment). Looking at Qupath repos, maybe it could be placed [here](https://github.com/qupath/qupath-extension-bioimageio) or if you plan to contribute resources (e.g., models), you could also create a new one. How does it sound? If you tell me where I can help you with the next steps =)

**Comment by petebankhead** [comment]
Thanks @oeway and @esgomezm !

Repo created at https://github.com/qupath/qupath-bioimage-io
No resources yet, but I'm optimistic that there will be one day...
