### ISSUE TITLE
Case sensitive folders in the collection (icy and Icy)

### ISSUE THREAD

**Issue by ivan-ea** [bioimage-io/collection-bioimage-io#574]
I ran into the problem below in Windows when trying to pull the collection (gh-pages branch)

````
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'partner_collection/icy/Icy/resource.yaml'
  'partner_collection/icy/icy/resource.yaml'
  'rdfs/icy/Icy/latest/rdf.yaml'
  'rdfs/icy/icy/latest/rdf.yaml'
  'rdfs/icy/Icy/latest/test_summary.yaml'
  'rdfs/icy/icy/latest/test_summary.yaml'
````

My guess is that 1 of them is the good one, so maybe the other could be eliminated @carlosuc3m?

**Comment by oeway** [comment]
Could you please change it into lower case? in general it's not recommended to use upper case in a path. so the ID for Icy should be `icy`. 
@FynnBe may comment on how to eliminate them.

**Comment by FynnBe** [comment]
once we decided for a version (captialized or not; I agree with @oeway  that we should try to use lower case if possible) then we can simply manually remove the other one from the gh-pages branch.
