### ISSUE TITLE
Spaces in animal names

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/collection-bioimage-io#702]
One (or more?) animal names contain spaces: 

https://github.com/bioimage-io/collection-bioimage-io/blob/0892cca8b13989795b8951d81ec40e3fca94b4ef/animals.yaml#L41 

Aka there's a bug in the bug :wink: 

Apologies in advance if this is being addressed somewhere - am a bit lost in the many branches.

**Comment by FynnBe** [comment]
it hasn't been an issue (no where did we specify that animal nicknames may not have spaces), but we should probably get rid of the spaces to use them as ids 👍 
If we keep want to be able to spell the animal correctly, we should probably use underscores to distinguish to hyphenated animal names, e.g. t-rex.
underscore sounds good?

**Comment by FynnBe** [comment]
we can change it then! I think I took the names from the unicode symbols, e.g. found here: https://www.compart.com/en/unicode/U+1F41E#UNC_DB

As a non-native I find ladybug more intuitive, but we have European funding... so ladybird?🤷

**Comment by jmetz** [comment]
Well, given the UKs self-exile from the EU, and that most english-language media consumed in the EU is likely to be US-based, maybe ladybug makes more sense. Personally I prefer ladybird though, so ... either should be fine :+1:

**Comment by FynnBe** [comment]
uh, other names are God's cow or lady cow.... 
we can also add them both (with the same symbol). This is an option for a future in which we feel animal names don't feel unique enough... 
For now I'd keep just one, see #703
